## Pytorch theory and Implementation

A Vector is a one dimensional tensor, similary a matrix is a 2-dimensional tensor and 3 dimensional array is another example of tensor.

A tensor is a fundamental data structure for neural networks. 


In [3]:
import torch

In [4]:
def activation(x):
    return 1/(1 + torch.exp(-x))

In [10]:
torch.manual_seed(7)

features = torch.randn((1, 5))
# features generation using torch.randn function of size (1, 5). 1 row 5 columns. It gets value from a normal distribution with a mean 0 and standard deviation of 1

weights = torch.randn_like(features)
# Generate random weights based on features describes above. The dimensions are based on the feature dimensions. these are values from a normal distribution

bias = torch.randn((1,1))
# bias of dimension of 1,1, it creates a single value from normal distribution

print(features)
print(weights)
print(bias)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[0.3177]])


In [13]:
# implement output part of the solution. Which means multiplying the features and weights and outputing it through a signmoid function
import numpy as np

#output = np.sum(np.dot(features, weights), bias)
# number of columns in A is equal to number of columns in B - Matrix multiplication rules.
output = torch.mm(features, weights.reshape(5, 1))
# this is one way of implementing the matrix multiplication
print(output)



tensor([[-1.9796]])
