## Pytorch theory and Implementation

A Vector is a one dimensional tensor, similary a matrix is a 2-dimensional tensor and 3 dimensional array is another example of tensor.

A tensor is a fundamental data structure for neural networks. 


In [4]:
import torch
print("success")

success


In [5]:
def activation(x):
    return 1/(1 + torch.exp(-x))
print("success")

success


In [6]:
torch.manual_seed(7)

features = torch.randn((1, 5))
# features generation using torch.randn function of size (1, 5). 1 row 5 columns. It gets value from a normal distribution with a mean 0 and standard deviation of 1

weights = torch.randn_like(features)
# Generate random weights based on features describes above. The dimensions are based on the feature dimensions. these are values from a normal distribution

bias = torch.randn((1,1))
# bias of dimension of 1,1, it creates a single value from normal distribution

print(features)
print(weights)
print(bias)
print("success")

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[0.3177]])
success


In [7]:
# implement output part of the solution. Which means multiplying the features and weights and outputing it through a signmoid function
import numpy as np

#output = np.sum(np.dot(features, weights), bias)
# number of columns in A is equal to number of columns in B - Matrix multiplication rules.
output = torch.mm(features, weights.reshape(5, 1)) 
# reshape maintains the same data but reshapes the tensor
# resize retains the new shape even if it involves missing some data points or removing fewa
# this is one way of implementing the matrix multiplication
print(output)

print("success")

tensor([[-1.9796]])
success


In [ ]:
## Stacking the layers

In [11]:
# generating some data
torch.manual_seed(7)

# features are 3 random normal variables
features = torch.randn((1,3))

# define the size of each input layer in our network
n_input = features.shape[1] # Number of input units, must match number of input features
n_hidden = 2 # Number of hidden units
n_output = 1 # Number of output units
W1 = torch.randn(n_input, n_hidden)

W2 = torch.randn(n_hidden, n_output)

B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

print("success")

3
3
success


In [ ]:
## Calculate the multiplayer output from the above layers using W1, W2, B1 and B2

In [24]:
layer1_output = torch.mm(features, W1.reshape(n_input, n_hidden)) + B1

output1 = activation(layer1_output)

# feeding the first layer output to the second hidden layer's input
layer2_output = torch.mm(output1, W2.reshape(n_hidden, n_output)) + B2

output = activation(layer2_output)
print(output)
# last layer gives out only one output
print("success")


tensor([[0.3171]])
success
