## Pytorch theory and Implementation

A Vector is a one dimensional tensor, similary a matrix is a 2-dimensional tensor and 3 dimensional array is another example of tensor.

A tensor is a fundamental data structure for neural networks. 


In [3]:
import torch

In [4]:
def activation(x):
    return 1/(1 + torch.exp(-x))

In [8]:
torch.manual_seed(7)

features = torch.randn((1, 5))
# features generation using torch.randn function of size (1, 5). 1 row 5 columns

weights = torch.randn_like(features)
# Generate random weights based on features describes above. The dimensions are based on the feature dimensions. these are values from a normal distribution

bias = torch.randn((1,1))
# bias of dimension of 1,1

print(features)
print(weights)
print(bias)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[0.3177]])
